# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_anuncio', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(upload_to='img/')),
                ('is_ativo', models.BooleanField(default=True)),
                ('is_doacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('autor', models.CharField(max_length=75)),
                ('edicao', models.CharField(max_length=10)),
                ('nivel_conservacao', models.CharField(choices=[('ruim', 'Ruim'), ('razoavel', 'Razoavel'), ('bom', 'Bom'), ('excelente', 'Excelente')], max_length=45)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_livros', to=settings.AUTH_USER_MODEL)),
                ('genero', models.ManyToManyField(to='core.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_desapegados', to=settings.AUTH_USER_MODEL)),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minha_transacao', to='core.Livro')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_adiquiridos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='livro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meu_anuncio', to='core.Livro'),
        ),
    ]
