# Generated by Django 2.0.3 on 2018-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_anuncio', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(upload_to='img/')),
                ('is_ativo', models.BooleanField(default=True)),
                ('is_doacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('autor', models.CharField(max_length=75)),
                ('edicao', models.CharField(max_length=10)),
                ('nivel_conservacao', models.CharField(choices=[('ruim', 'ruim'), ('razoavel', 'razoavel'), ('bom', 'bom'), ('excelente', 'excelente')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
