# Generated by Django 2.0.3 on 2018-03-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='is_doacao',
        ),
        migrations.AddField(
            model_name='livro',
            name='is_doacao',
            field=models.BooleanField(default=True),
        ),
    ]
