# Generated by Django 2.0.3 on 2018-03-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180318_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateField(auto_now=True),
        ),
    ]
