# Generated by Django 2.0.3 on 2018-03-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transacao_data_transacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='foto',
        ),
        migrations.AddField(
            model_name='livro',
            name='foto',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
