# Generated by Django 2.0.3 on 2018-03-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180321_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='is_doacao',
        ),
    ]
