# Generated by Django 2.0.3 on 2018-03-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cellphone',
            new_name='telefone',
        ),
    ]
